### ISSUE TITLE
Would it be possible to have a sorter command line for ng generate @ngxs/schematics ?

### ISSUE THREAD

**Issue by ahnpnl** [ngxs/schematics#15]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[x] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
In my opinion, `ng generate @ngxs/schematics ...` is kind of a long command. Would you be possible to have a sorter one, e.g `ng generate ngxs ...` (inspired from [nrwl](https://nrwl.io/nx/guide-setting-up-ngrx))

## Expected behavior
**N.A.**

## Minimal reproduction of the problem with instructions

**N.A.**

## What is the motivation / use case for changing the behavior?
It is faster to type `ng generate ngxs` comparing to `ng generate @ngxs/schematics`.

## Environment

<pre><code>
Libs:
- @angular/core version: 7.1.0
- @ngxs/store version: 3.3.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.14.0
- Platform:  Mac, Windows

Others:
N.A.

**Comment by adammedford** [comment]
Its a little odd that you would use mention using `ng generate` instead of `ng g` in an issue about command length.

To achieve what @nrwl/schematics has you'll need to modify your **angular.json** and add a _cli_ entry if there isn't one. The _cli_ entry should be an object - you'll need a line in it that says `"defaultCollection": "@ngxs/schematics"`

If you're in a Nrwl Nx workspace you will already have this value set to '@nrwl/schematics'. Know that changing this means that now to use any nrwl schematics you'll have to use the longform - `ng g @nrwl/schematics:library`

There's also the option of using Angular Console (another nrwl project) when Ngxs integration is ready. You'll notice that even in Angular Console nrwl's own commands are the longer version as it doesn't use the workspace's default collection.

**Comment by ahnpnl** [comment]
Thank you for the guide. I'll follow it 👍
